### ISSUE TITLE
Use CDN for Wing

### ISSUE THREAD

**Issue by kbrsh** [jondcoleman/file-search-electron#1]
Currently you are linking to Wing's local file, it uses an outdated version of Wing, and is slow. 

You might want to use [CDNjs](https://cdnjs.com/libraries/wingcss), or [jsDelivr](http://www.jsdelivr.com/projects/wing)

**Comment by jondcoleman** [comment]
@KingPixil I need this to work offline though.

**Comment by jondcoleman** [comment]
I'm going to be dowloading and I'll grab it from the CDN when I do.  Just plugged it in for dev.

**Comment by kbrsh** [comment]
cool, I will be updating a bug fix on Wing, 0.1.7 is coming!
